#!/bin/bash
# cvmfs_server_select.sh
#
# Ranks CVMFS servers for neurodesk.ardc.edu.au by measured download
# throughput and writes the repository config with the fastest server first
# and the runners-up as fallbacks. The CVMFS client walks CVMFS_SERVER_URL in
# order (CVMFS_USE_GEOAPI=no), so the ranking directly controls which server
# is used, and the failover settings in /etc/cvmfs/default.local move clients
# off a degraded primary at runtime.
#
# Selection happens in two stages so that throughput measurements stay clean:
#   Stage 1: probe every candidate host in parallel with a tiny fetch of
#            .cvmfspublished (cheap; concurrent probes do not distort each
#            other) to drop unreachable hosts and shortlist finalists.
#   Stage 2: download the root catalog (~1 MB) twice from each finalist,
#            one host at a time, and score by the best observed speed.
#
# All probe URLs carry a unique cache-busting query string. Without it, CDN
# edges (openhtc.io/Cloudflare) answer from their cache at warm speeds that
# most users never see: real workloads fetch long-tail container objects that
# are cold at the edge, so ranking must reflect the cold path (edge -> origin
# -> client). Origin servers ignore the query string; Cloudflare keys its
# cache on it, so every probe is a guaranteed cache miss.
#
# A successful ranking is cached and reused on later boots while it is
# younger than the TTL and its primary server still responds; a stale or
# unhealthy cache triggers a full re-probe.
#
# Usage: cvmfs_server_select.sh [--force-probe]
#   --force-probe  ignore the cached selection and probe again
#
# Exit codes: 0 = ranked config written (fresh or cached)
#             1 = no server measurable; static fallback config written
#
# Environment overrides (mainly for testing, see docs/environment-variables.md):
#   NEURODESKTOP_CVMFS_HOST_POOL              whitespace-separated http://host[:port] list
#   NEURODESKTOP_CVMFS_SELECTION_TTL_SECONDS  cache lifetime (default 604800 = 7 days)
#   NEURODESKTOP_CVMFS_TARGET_CONFIG          config file to write
#   NEURODESKTOP_CVMFS_CACHE_FILE             cache file location

set -o pipefail

REPO_FQRN="neurodesk.ardc.edu.au"
TARGET_CONFIG="${NEURODESKTOP_CVMFS_TARGET_CONFIG:-/etc/cvmfs/config.d/${REPO_FQRN}.conf}"
CACHE_FILE="${NEURODESKTOP_CVMFS_CACHE_FILE:-${HOME}/.cache/neurodesktop/cvmfs-selection.env}"
TTL_SECONDS="${NEURODESKTOP_CVMFS_SELECTION_TTL_SECONDS:-604800}"
KEYS_DIR="/etc/cvmfs/keys/ardc.edu.au/"
NUM_SERVERS=4     # servers written to CVMFS_SERVER_URL (primary + fallbacks)
NUM_FINALISTS=5   # reachable hosts that get the throughput measurement

# Candidate pool: the direct Stratum-1 servers plus the Cloudflare-fronted
# (openhtc.io) CDN endpoints, with the ports they really serve on. Both kinds
# are probed the same way so CDN endpoints win or lose on measurement, not by
# category.
DEFAULT_HOST_POOL="
http://cvmfs-geoproximity.neurodesk.org
http://cvmfs.neurodesk.org
http://cvmfs-brisbane.neurodesk.org
http://cvmfs-melbourne.neurodesk.org
http://cvmfs-sydney.neurodesk.org
http://cvmfs-perth.neurodesk.org
http://cvmfs-jetstream.neurodesk.org
http://cvmfs-frankfurt.neurodesk.org
http://cvmfs01.nikhef.nl:8000
http://cvmfs-s1bnl.opensciencegrid.org:8000
http://cvmfs-s1goc.opensciencegrid.org:8000
http://cvmfs-stratum-one.ihep.ac.cn
http://sampacs01.if.usp.br:8000
http://s1brisbane-cvmfs.openhtc.io
http://s1melbourne-cvmfs.openhtc.io
http://s1nikhef-cvmfs.openhtc.io
http://s1osggoc-cvmfs.openhtc.io:8080
http://s1bnl-cvmfs.openhtc.io
http://s1sampa-cvmfs.openhtc.io:8080
"
HOST_POOL="${NEURODESKTOP_CVMFS_HOST_POOL:-${DEFAULT_HOST_POOL}}"

# Static fallback when nothing is measurable (e.g. captive portal lets DNS
# through but blocks HTTP): geo-DNS plus CDN entry points, GeoAPI ordering.
# Keep in sync with config/cvmfs/neurodesk.ardc.edu.au.conf.
FALLBACK_SERVER_URL="http://cvmfs-geoproximity.neurodesk.org/cvmfs/@fqrn@;http://cvmfs.neurodesk.org/cvmfs/@fqrn@;http://s1brisbane-cvmfs.openhtc.io/cvmfs/@fqrn@;http://s1nikhef-cvmfs.openhtc.io/cvmfs/@fqrn@"

FORCE_PROBE=false
if [ "${1:-}" = "--force-probe" ]; then
    FORCE_PROBE=true
fi

log() { echo "[cvmfs-select] $*"; }

# Cache-busting query value: forces a cache MISS on CDN edges so probes
# measure the cold path. The caller-supplied tag makes values unique within a
# run (RANDOM alone can repeat across forked subshells on older bash); epoch,
# PID and RANDOM make them unique across runs so a value warmed by a previous
# run is never reused.
cache_bust() { echo "cvmfsselect=$(date +%s)-$$-${RANDOM}-$1"; }

write_config() {
    local server_url="$1"
    local geoapi="$2"
    mkdir -p "$(dirname "$TARGET_CONFIG")"
    cat > "$TARGET_CONFIG" <<EOF
# Auto-generated by cvmfs_server_select.sh - do not edit.
# Servers are ordered by measured download throughput; the client walks the
# list in order and fails over using the settings in /etc/cvmfs/default.local.
CVMFS_USE_GEOAPI=${geoapi}
CVMFS_SERVER_URL="${server_url}"
CVMFS_KEYS_DIR="${KEYS_DIR}"
EOF
}

# Quick health check: does this host serve the repository manifest?
host_ok() {
    local base="$1"
    local code
    code=$(curl --no-keepalive --connect-timeout 3 --max-time 8 -s -o /dev/null \
        -w "%{http_code}" "${base}/cvmfs/${REPO_FQRN}/.cvmfspublished")
    [ "$code" = "200" ]
}

# ── Cache fast-path ──────────────────────────────────────────────────────────
if [ "$FORCE_PROBE" != "true" ] && [ -f "$CACHE_FILE" ]; then
    CACHED_CVMFS_SERVER_URL=""
    CACHED_TIMESTAMP=""
    # shellcheck source=/dev/null
    . "$CACHE_FILE"
    cache_valid=false
    case "$CACHED_TIMESTAMP" in
        ''|*[!0-9]*) ;;
        *)
            now=$(date +%s)
            age=$((now - CACHED_TIMESTAMP))
            if [ -n "$CACHED_CVMFS_SERVER_URL" ] && [ "$age" -ge 0 ] && [ "$age" -lt "$TTL_SECONDS" ]; then
                cache_valid=true
            fi
            ;;
    esac
    if [ "$cache_valid" = "true" ]; then
        primary_base="${CACHED_CVMFS_SERVER_URL%%;*}"
        primary_base="${primary_base%/cvmfs/@fqrn@}"
        if host_ok "$primary_base"; then
            log "Using cached server selection (age ${age}s): ${CACHED_CVMFS_SERVER_URL}"
            write_config "$CACHED_CVMFS_SERVER_URL" no
            exit 0
        fi
        log "Cached primary server failed health check - re-probing."
    else
        log "Cache is stale or invalid - re-probing."
    fi
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# ── Stage 1: reachability + latency prefilter (parallel) ────────────────────
# Fetch .cvmfspublished twice per host and keep the faster time (a min over
# two samples filters transient hiccups). Cache-busted so CDN edges answer
# via their origin, not from a warm edge cache — otherwise CDN hosts with a
# slow cold path would crowd the direct servers out of the finalist list.
# The manifest is also parsed for the root catalog hash so stage 2 can skip
# refetching it. Hosts that do not return a parseable manifest are dropped.
probe_host() {
    local base="$1"
    local out_file="$2"
    local pub_file="$3"
    local repo_url="${base}/cvmfs/${REPO_FQRN}"
    local best="" i out t code
    for i in 1 2; do
        out=$(curl --no-keepalive --connect-timeout 3 --max-time 8 -s \
            -w "%{time_total} %{http_code}" -o "$pub_file" \
            "${repo_url}/.cvmfspublished?$(cache_bust "pub${i}")")
        t=$(echo "$out" | awk '{print $1}')
        code=$(echo "$out" | awk '{print $2}')
        if [ "$code" = "200" ]; then
            if [ -z "$best" ] || [ "$(awk "BEGIN {print ($t < $best) ? 1 : 0}")" = "1" ]; then
                best="$t"
            fi
        fi
    done
    if [ -z "$best" ]; then
        log "  $base unreachable"
        return
    fi
    local catalog_hash
    catalog_hash=$(awk '/^C/{print substr($0,2); exit}' "$pub_file")
    if [ -z "$catalog_hash" ]; then
        log "  $base returned an invalid repository manifest"
        return
    fi
    log "  $base reachable (${best}s)"
    echo "$best $base $catalog_hash" > "$out_file"
}

log "Stage 1: probing candidate hosts in parallel..."
mkdir -p "$tmpdir/lat" "$tmpdir/pub"
i=0
for base in $HOST_POOL; do
    probe_host "$base" "$tmpdir/lat/$i" "$tmpdir/pub/$i" &
    i=$((i + 1))
done
wait

reachable=$(cat "$tmpdir"/lat/* 2>/dev/null | sort -n)

if [ -z "$reachable" ]; then
    log "WARNING: no CVMFS server reachable - writing static fallback config."
    write_config "$FALLBACK_SERVER_URL" yes
    exit 1
fi

# ── Stage 2: throughput measurement (sequential, so transfers don't share
# bandwidth and distort each other's numbers) ────────────────────────────────
# Download the root catalog twice, each time with a fresh cache-busting query
# so both fetches take the cold path, and keep the best speed (max over two
# cold samples filters transient client-side dips without rewarding warm
# caches).
measure_throughput() {
    local base="$1"
    local catalog_hash="$2"
    local url="${base}/cvmfs/${REPO_FQRN}/data/${catalog_hash:0:2}/${catalog_hash:2}C"
    local best=0 i out speed code
    for i in 1 2; do
        out=$(curl --no-keepalive --connect-timeout 3 --max-time 10 -s \
            -w "%{speed_download} %{http_code}" -o /dev/null "${url}?$(cache_bust "cat${i}")")
        speed=$(echo "$out" | awk '{printf "%d", $1}')
        code=$(echo "$out" | awk '{print $2}')
        if [ "$code" = "200" ] && [ "$speed" -gt "$best" ]; then
            best="$speed"
        fi
    done
    echo "$best"
}

log "Stage 2: measuring throughput of the ${NUM_FINALISTS} lowest-latency hosts..."
: > "$tmpdir/scores"
finalist_count=0
while read -r _lat base catalog_hash; do
    [ -z "$base" ] && continue
    if [ "$finalist_count" -ge "$NUM_FINALISTS" ]; then
        break
    fi
    speed=$(measure_throughput "$base" "$catalog_hash")
    log "  $base: $((speed / 1024)) KB/s"
    echo "$speed $base" >> "$tmpdir/scores"
    finalist_count=$((finalist_count + 1))
done <<EOF
$reachable
EOF

ranked=$(sort -rn "$tmpdir/scores" | awk '$1 > 0 {print $2}')
if [ -z "$ranked" ]; then
    log "WARNING: throughput measurement failed for all finalists - ranking by latency instead."
    ranked=$(echo "$reachable" | awk '{print $2}')
fi

# Build CVMFS_SERVER_URL: best hosts first, padded with the remaining
# reachable hosts (in latency order) if fewer than NUM_SERVERS were scored.
SERVER_URL=""
n=0
for base in $ranked $(echo "$reachable" | awk '{print $2}'); do
    [ "$n" -ge "$NUM_SERVERS" ] && break
    entry="${base}/cvmfs/@fqrn@"
    case ";${SERVER_URL};" in
        *";${entry};"*) continue ;;
    esac
    if [ -z "$SERVER_URL" ]; then
        SERVER_URL="$entry"
    else
        SERVER_URL="${SERVER_URL};${entry}"
    fi
    n=$((n + 1))
done

# Infrastructure diversity: the fastest servers are often all Cloudflare
# (openhtc.io) endpoints. Append the best non-CDN host as a last-resort
# fallback so a CDN-wide outage cannot take out the entire chain.
if ! printf '%s' "$SERVER_URL" | tr ';' '\n' | grep -qv "openhtc\.io"; then
    best_direct=$(echo "$reachable" | awk '{print $2}' | grep -v "openhtc\.io" | head -n 1)
    if [ -n "$best_direct" ]; then
        SERVER_URL="${SERVER_URL};${best_direct}/cvmfs/@fqrn@"
        log "Appended ${best_direct} as non-CDN fallback for infrastructure diversity."
    fi
fi

log "Ranked server list: ${SERVER_URL}"
write_config "$SERVER_URL" no

mkdir -p "$(dirname "$CACHE_FILE")"
cat > "$CACHE_FILE" <<EOF
# CVMFS server selection cache - auto-generated by cvmfs_server_select.sh
CACHED_CVMFS_SERVER_URL="${SERVER_URL}"
CACHED_TIMESTAMP=$(date +%s)
EOF
log "Saved CVMFS server selection to cache: ${CACHE_FILE}"
exit 0
