name: Test binder

on:
  workflow_dispatch:
  push:
    paths:
      - binder/Dockerfile
    branches:
      main

jobs:
  test_binder:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        server: ["https://playtest.neurodesk.org/build/gh", "https://play-sydney.neurodesk.org/build/gh"]
    steps:
    - uses: actions/checkout@v3
    - name: Build binder
      run: curl "${{ matrix.server }}/$GITHUB_REPOSITORY/$GITHUB_REF_NAME"
